config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'

  get 'dashboard/index'
  resources :exercise_types
  resources :exercises
  resources :grubs
  resources :steps
  resources :weights

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @weights = Weight.all

    @daily_steps = Step.daily_total
    @weekly_steps = Step.weekly_total
    @monthly_steps = Step.monthly_total

    @daily_grubs = Grub.daily_total
    @daily_exercises = Exercise.daily_total

    @daily_net_calories = @daily_grubs - @daily_exercises

    @daily_total = Weight.daily_total

  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<h1>Welcome to Health-O-Meter</h1>
<h2>Check out your stats or submit a new entry.</h2>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @weights.each do |weight| %>
      <tr>
        <td><%= weight.amount %></td>
        <td><%= weight.date %></td>
        <td><%= link_to 'Show', weight %></td>
        <td><%= link_to 'Edit', edit_weight_path(weight) %></td>
        <td><%= link_to 'Destroy', weight, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>



<h3>Daily Step Amount: <%= @daily_steps %> </h3>
<h3>Monthly Step Amount: <%= @monthly_steps %> </h3>
<h3>Daily Calories Burned: <%= @daily_net_calories %> </h3>
<h3>Today's Weight: <%= @daily_total %> </h3>


<%= link_to 'New Weight', new_weight_path %><br>
<%= link_to 'New Step', new_step_path %><br>
<%= link_to 'Add Calories Eaten', new_grub_path %><br>
<%= link_to 'Add Calories Burned', new_exercise_path %><br>
<%= link_to 'Add Exercise Type', new_exercise_type_path %><br>