config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'

  get 'dashboard/index'
  resources :exercise_types
  resources :exercises
  resources :grubs
  resources :steps
  resources :weights

end

app/controllers/exercise_types_controller.rb
class ExerciseTypesController < ApplicationController
  before_action :set_exercise, only: [:show, :edit, :update, :destroy]


  def index
        @exercise_types = ExerciseType.all
  end

  def show
  end

  def new
      @exercise_type = ExerciseType.new
  end

  def edit
  end

  def create

      @exercise_type = ExerciseType.new(exercise_type_params)
      respond_to do |format|
        if @exercise_type.save
          format.html { redirect_to @exercise_type, notice: 'exercise type was successfully created.' }
        else
          format.html { render :new }
        end
      end

  end

  def destroy
  end

  def update
  end



private
  # Use callbacks to share common setup or constraints between actions.
  def set_exercise
    @exercise_types = ExerciseType.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def exercise_type_params
    params.require(:exercise_type).permit(:name)
  end


end

app/helpers/exercise_types_helper.rb
module ExerciseTypesHelper
end

app/views/exercise_types/_form.html.erb
<%= form_for(@exercise_type) do |f| %>
  <% if @exercise_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exercise_type.errors.count, "error") %> prohibited this exercise from being saved:</h2>

      <ul>
      <% @exercise_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exercise_types/create.html.erb
<h1>ExerciseTypes#create</h1>
<p>Find me in app/views/exercise_types/create.html.erb</p>

app/views/exercise_types/destroy.html.erb
<h1>ExerciseTypes#destroy</h1>
<p>Find me in app/views/exercise_types/destroy.html.erb</p>

app/views/exercise_types/edit.html.erb
<h1>ExerciseTypes#edit</h1>
<p>Find me in app/views/exercise_types/edit.html.erb</p>

app/views/exercise_types/index.html.erb
<h1>ExerciseTypes#index</h1>
<p>Find me in app/views/exercise_types/index.html.erb</p>

<p id="notice"><%= notice %></p>

<h1>Exercise Types!</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exercise_types.each do |exercise| %>
      <tr>

        <td><%= exercise.name %></td>
        <td><%= exercise.created_at %></td>
        <td><%= exercise.updated_at %></td>
        <td><%= link_to 'Details', exercise %></td>
        <td><%= link_to 'Edit', edit_exercise_path(exercise) %></td>
        <td><%= link_to 'Remove', exercise, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add Another Entry', new_exercise_type_path %>

app/views/exercise_types/new.html.erb
<h1>Add New Exercise Type</h1>

<%= render 'form' %>

<%= link_to 'Back to Dashboard', dashboard_index_path %>

app/views/exercise_types/show.html.erb
<h1>ExerciseTypes#show</h1>
<p>Find me in app/views/exercise_types/show.html.erb</p>


<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @exercise_types.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @exercise_types.created_at %>
</p>


<%= link_to 'Back', exercise_type_path %>

app/views/exercise_types/update.html.erb
<h1>ExerciseTypes#update</h1>
<p>Find me in app/views/exercise_types/update.html.erb</p>