config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'

  get 'dashboard/index'
  resources :exercise_types
  resources :exercises
  resources :grubs
  resources :steps
  resources :weights

end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :set_exercise, only: [:show, :edit, :update, :destroy]

  # GET /exercises
  # GET /exercises.json
  def index
    @exercises = Exercise.all
  end

  # GET /exercises/1
  # GET /exercises/1.json
  def show
  end

  # GET /exercises/new
  def new
    @exercise = Exercise.new
  end

  # GET /exercises/1/edit
  def edit
  end

  # POST /exercises
  # POST /exercises.json
  def create
    @exercise = Exercise.new(exercise_params)

    respond_to do |format|
      if @exercise.save
        format.html { redirect_to @exercise, notice: 'exercise was successfully created.' }
        format.json { render :show, status: :created, location: @exercise }
      else
        format.html { render :new }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exercises/1
  # PATCH/PUT /exercises/1.json
  def update
    respond_to do |format|
      if @exercise.update(exercise_params)
        format.html { redirect_to @exercise, notice: 'exercise was successfully updated.' }
        format.json { render :show, status: :ok, location: @exercise }
      else
        format.html { render :edit }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exercises/1
  # DELETE /exercises/1.json
  def destroy
    @exercise.destroy
    respond_to do |format|
      format.html { redirect_to exercises_url, notice: 'exercise was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exercise
      @exercise = Exercise.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exercise_params
      params.require(:exercise).permit(:amount, :date, :exercise_type_id)
    end
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/views/exercises/_form.html.erb
<%= form_for(@exercise) do |f| %>
  <% if @exercise.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exercise.errors.count, "error") %> prohibited this exercise from being saved:</h2>

      <ul>
      <% @exercise.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :amount %><br>
    <%= f.number_field :amount %>
  </div>

  <div class="field">
    <%= f.label :exercise_type_id %><br>
    <%= f.select :exercise_type_id, options_for_select(ExerciseType.all.map{|s| [s.name, s.id]}) %>
  </div>



  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exercises/create.html.erb
<h1>Exercises#create</h1>
<p>Find me in app/views/exercises/create.html.erb</p>

app/views/exercises/destroy.html.erb
<h1>Exercises#destroy</h1>
<p>Find me in app/views/exercises/destroy.html.erb</p>

app/views/exercises/edit.html.erb
<h1>Exercises#edit</h1>
<p>Find me in app/views/exercises/edit.html.erb</p>

app/views/exercises/index.html.erb
<h1>Exercises#index</h1>
<p>Find me in app/views/exercises/index.html.erb</p>



<p id="notice"><%= notice %></p>

<h1>Exercises</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exercises.each do |exercise| %>
      <tr>

        <td><%= exercise.amount %></td>
        <td><%= exercise.date %></td>
        <td><%= link_to 'Details', exercise %></td>
        <td><%= link_to 'Edit', edit_exercise_path(exercise) %></td>
        <td><%= link_to 'Remove', exercise, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add Another Entry', new_exercise_path %>

app/views/exercises/new.html.erb
<h1>Add New Exercise</h1>

<%= render 'form' %>

<%= link_to 'Back to Dashboard', dashboard_index_path %>

app/views/exercises/show.html.erb
<h1>Exercises#show</h1>


<p id="notice"><%= notice %></p>

<p>
  <strong>amount Burned:</strong>
  <%= @exercise.amount %>
</p>

<p>
  <strong>Exercise Type:</strong>
  <%= @exercise.exercise_type_id %>
</p>




<p>
  <strong>Date:</strong>
  <%= @exercise.date %>
</p>




<%= link_to 'Edit', edit_exercise_path(@exercise) %> |
<%= link_to 'Back', exercises_path %>

app/views/exercises/update.html.erb
<h1>Exercises#update</h1>
<p>Find me in app/views/exercises/update.html.erb</p>